/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Tela.Mensagem;

import Classes.Funcoes;
import Classes.Mensagem;
import java.awt.Window;

@SuppressWarnings("serial")
public class TelaMensagemConfirmar extends javax.swing.JDialog {
    private final Mensagem mensagem = new Mensagem();
    private final Funcoes funcao = new Funcoes();
    
    public TelaMensagemConfirmar(Window parent, boolean modal) {
        super(parent, modal ? ModalityType.APPLICATION_MODAL : ModalityType.MODELESS);
        setUndecorated(true);
        initComponents();
        iniciar();
        funcao.aplicarEfeitoMouse(botaoSim);
        funcao.aplicarEfeitoMouse(botaoNao);
    }

    private void iniciar(){
        labelTitulo.setText(mensagem.getTitulo());
        labelMensagem.setText(mensagem.getMensagem());
        labelMensagem2.setText(mensagem.getMensagem2());
        botaoSim.requestFocus();
        getRootPane().setDefaultButton(botaoSim);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bordaSim = new javax.swing.JPanel();
        botaoSim = new javax.swing.JButton();
        labelMensagem = new javax.swing.JLabel();
        labelMensagem2 = new javax.swing.JLabel();
        bordaNao = new javax.swing.JPanel();
        botaoNao = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        icone = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        iconePrograma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bordaSim.setBackground(new java.awt.Color(255, 255, 255));
        bordaSim.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        bordaSim.setForeground(new java.awt.Color(0, 0, 0));
        bordaSim.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoSim.setBackground(new java.awt.Color(204, 204, 204));
        botaoSim.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        botaoSim.setForeground(new java.awt.Color(0, 0, 0));
        botaoSim.setText("SIM");
        botaoSim.setToolTipText("Clique para confirmar");
        botaoSim.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoSim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSimActionPerformed(evt);
            }
        });
        bordaSim.add(botaoSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jPanel2.add(bordaSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 140, 40));

        labelMensagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelMensagem.setForeground(new java.awt.Color(0, 0, 0));
        labelMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensagem.setText("TEXTO DA MENSAGEM");
        jPanel2.add(labelMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 30));

        labelMensagem2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelMensagem2.setForeground(new java.awt.Color(0, 0, 0));
        labelMensagem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensagem2.setText("TEXTO DA MENSAGEM2");
        jPanel2.add(labelMensagem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 460, 30));

        bordaNao.setBackground(new java.awt.Color(255, 255, 255));
        bordaNao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        bordaNao.setForeground(new java.awt.Color(0, 0, 0));
        bordaNao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoNao.setBackground(new java.awt.Color(204, 204, 204));
        botaoNao.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        botaoNao.setForeground(new java.awt.Color(0, 0, 0));
        botaoNao.setText("NÃO");
        botaoNao.setToolTipText("Clique para cancelar");
        botaoNao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoNao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoNao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNaoActionPerformed(evt);
            }
        });
        bordaNao.add(botaoNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jPanel2.add(bordaNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 140, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 460, 120));

        jPanel3.setBackground(new java.awt.Color(228, 228, 228));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        icone.setBackground(new java.awt.Color(228, 228, 228));
        icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pergunta.png"))); // NOI18N
        icone.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(icone);
        icone.setBounds(2, 0, 80, 80);

        labelTitulo.setBackground(new java.awt.Color(228, 228, 228));
        labelTitulo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 20)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("TEXTO DO TITULO");
        jPanel3.add(labelTitulo);
        labelTitulo.setBounds(1, 0, 460, 76);

        iconePrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LogoMarcaMensagem.png"))); // NOI18N
        jPanel3.add(iconePrograma);
        iconePrograma.setBounds(380, 0, 80, 80);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSimActionPerformed
         mensagem.getAcao().run();
         this.dispose();
    }//GEN-LAST:event_botaoSimActionPerformed

    private void botaoNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNaoActionPerformed
         this.dispose();
    }//GEN-LAST:event_botaoNaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMensagemConfirmar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMensagemConfirmar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMensagemConfirmar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMensagemConfirmar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaMensagemConfirmar dialog = new TelaMensagemConfirmar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bordaNao;
    private javax.swing.JPanel bordaSim;
    private javax.swing.JButton botaoNao;
    private javax.swing.JButton botaoSim;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel iconePrograma;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelMensagem;
    private javax.swing.JLabel labelMensagem2;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
