/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Tela.Mensagem;

import Classes.Funcoes;
import Classes.Mensagem;
import java.awt.Window;
import javax.swing.Timer;

@SuppressWarnings("serial")
public class TelaMensagens extends javax.swing.JDialog {
    private final Mensagem mensagem = new Mensagem();
    private final Funcoes funcao = new Funcoes();
    
    public TelaMensagens(Window parent, boolean modal) {
        super(parent, modal ? ModalityType.APPLICATION_MODAL : ModalityType.MODELESS);
        setUndecorated(true);
        initComponents();
        iniciar();
        funcao.aplicarEfeitoMouse(botaoConfirmar);
        if("informacao".equals( mensagem.getTipo())){
            new Timer(1700, (e) -> this.dispose()).start();
        }
    }

    private void iniciar(){
        if (null == mensagem.getTipo()){
            icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/informacao.png")));
        }else switch (mensagem.getTipo()) {
            case "erro":
                icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/erro.png")));
                break;
            case "aviso":
                icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aviso.png")));
                break;
            case "informacao":
                icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/informacao2.png")));
                break;
            default:
                icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/informacao.png")));
                break;
        }
        labelTitulo.setText(mensagem.getTitulo());
        labelMensagem.setText(mensagem.getMensagem());
        labelMensagem2.setText(mensagem.getMensagem2());
        botaoConfirmar.requestFocus();
        getRootPane().setDefaultButton(botaoConfirmar);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bordaConfirmar = new javax.swing.JPanel();
        botaoConfirmar = new javax.swing.JButton();
        labelMensagem = new javax.swing.JLabel();
        labelMensagem2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        iconePrograma = new javax.swing.JLabel();
        icone = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bordaConfirmar.setBackground(new java.awt.Color(255, 255, 255));
        bordaConfirmar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        bordaConfirmar.setForeground(new java.awt.Color(0, 0, 0));
        bordaConfirmar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoConfirmar.setBackground(new java.awt.Color(204, 204, 204));
        botaoConfirmar.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        botaoConfirmar.setForeground(new java.awt.Color(0, 0, 0));
        botaoConfirmar.setText("OK");
        botaoConfirmar.setToolTipText("Clique para confirmar leitura");
        botaoConfirmar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });
        bordaConfirmar.add(botaoConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jPanel2.add(bordaConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 140, 40));

        labelMensagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelMensagem.setForeground(new java.awt.Color(0, 0, 0));
        labelMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensagem.setText("TEXTO DA MENSAGEM");
        jPanel2.add(labelMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 30));

        labelMensagem2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelMensagem2.setForeground(new java.awt.Color(0, 0, 0));
        labelMensagem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensagem2.setText("TEXTO DA MENSAGEM2");
        jPanel2.add(labelMensagem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 460, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 460, 120));

        jPanel3.setBackground(new java.awt.Color(228, 228, 228));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        iconePrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LogoMarcaMensagem.png"))); // NOI18N
        jPanel3.add(iconePrograma);
        iconePrograma.setBounds(380, 0, 80, 80);

        icone.setBackground(new java.awt.Color(228, 228, 228));
        icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/informacao2.png"))); // NOI18N
        icone.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(icone);
        icone.setBounds(2, 0, 80, 80);

        labelTitulo.setBackground(new java.awt.Color(228, 228, 228));
        labelTitulo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 20)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("TEXTO DO TITULO");
        jPanel3.add(labelTitulo);
        labelTitulo.setBounds(1, 0, 460, 76);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaMensagens dialog = new TelaMensagens(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bordaConfirmar;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel iconePrograma;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelMensagem;
    private javax.swing.JLabel labelMensagem2;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
