/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Tela.Usuario;

import Classes.Funcoes;
import Classes.Usuario;
import Classes.UsuarioAtual;
import java.awt.Window;


@SuppressWarnings("serial")
public class ConfirmarUsuarioAtual extends javax.swing.JDialog {
    private final Funcoes funcao = new Funcoes();
    private final UsuarioAtual usuarioAtual = new UsuarioAtual();
    
    public ConfirmarUsuarioAtual(Window parent, boolean modal) {
        super(parent, modal ? ModalityType.APPLICATION_MODAL : ModalityType.MODELESS);
        setUndecorated(true);
        setResizable(false);
        initComponents();
        nomeText.requestFocus();
        funcao.aplicarEfeitoMouse(botaoMenu);  
        funcao.aplicarEfeitoMouse(botaoConfirmar); 
        digitacao();
    }
    
    private void digitacao(){
        funcao.limitarCaracteres(nomeText, 50); 
        funcao.limitarCaracteres(senhaText, 20); 
        funcaoEnabled();
    }
    
    private void adicionarLegendas() {
        funcao.validarBotaoComDica(botaoConfirmar, "Clique para confirmar autenticação");
    }
    
    private boolean elegivelSalvar(){
        return funcao.validarCamposPreenchidos(nomeText, senhaText);
    }
    
    private void funcaoEnabled(){
        botaoConfirmar.setEnabled(elegivelSalvar());
        botaoConfirmar.setOpaque(elegivelSalvar());
        adicionarLegendas();
    }
    
    private void confirmar() {
        if (!elegivelSalvar()) {
            funcao.MensagensJDialog(ConfirmarUsuarioAtual.this, "Preencha os campos corretamente!", "", "ATENÇÃO", "aviso");
            return;
        }

        String usuarioDigitado = nomeText.getText().trim();
        String senhaDigitada = new String(senhaText.getPassword()).trim();

        // Valida a senha com hash e salt do usuário atual
        boolean senhaCorreta;
        try {
            senhaCorreta = Usuario.validarSenha(
                senhaDigitada,
                usuarioAtual.getSenhaHash(),
                usuarioAtual.getSalt()
            );
        } catch (Exception e) {
            e.printStackTrace();
            funcao.MensagensJDialog(this, "Erro ao validar a senha!", "", "ERRO", "erro");
            return;
        }

        if (!usuarioDigitado.equals(usuarioAtual.getNome()) || !senhaCorreta) {
            funcao.MensagensJDialog(ConfirmarUsuarioAtual.this, "Usuário ou Senha inválidos!", "", "ERRO", "erro");
            return;
        }

        // Executa a ação definida
        Runnable acao = UsuarioAtual.getAcao();
        if (acao != null) {
            acao.run();
        }

        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bordaSalvar = new javax.swing.JPanel();
        botaoConfirmar = new javax.swing.JButton();
        painelDataReposicao = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        senhaText = new javax.swing.JPasswordField();
        nomeText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botaoMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(210, 164, 2));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LogoMarca.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("AUTENTICAÇÃO");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 60));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 430, 60);

        bordaSalvar.setBackground(new java.awt.Color(255, 255, 255));
        bordaSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        bordaSalvar.setForeground(new java.awt.Color(0, 0, 0));
        bordaSalvar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoConfirmar.setBackground(new java.awt.Color(210, 164, 2));
        botaoConfirmar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        botaoConfirmar.setForeground(new java.awt.Color(0, 0, 0));
        botaoConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CONFIRMAR.png"))); // NOI18N
        botaoConfirmar.setText("CONFIRMAR");
        botaoConfirmar.setToolTipText("");
        botaoConfirmar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoConfirmar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botaoConfirmar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });
        bordaSalvar.add(botaoConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 89, 59));

        jPanel1.add(bordaSalvar);
        bordaSalvar.setBounds(10, 320, 91, 62);

        painelDataReposicao.setBackground(new java.awt.Color(255, 255, 255));
        painelDataReposicao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "USUÁRIO ATUAL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(0, 0, 102))); // NOI18N
        painelDataReposicao.setForeground(new java.awt.Color(0, 102, 153));
        painelDataReposicao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Usuário:");
        painelDataReposicao.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 230, -1));

        senhaText.setBackground(new java.awt.Color(255, 255, 255));
        senhaText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        senhaText.setForeground(new java.awt.Color(0, 0, 0));
        senhaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaTextActionPerformed(evt);
            }
        });
        senhaText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                senhaTextKeyReleased(evt);
            }
        });
        painelDataReposicao.add(senhaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 230, -1));

        nomeText.setBackground(new java.awt.Color(255, 255, 255));
        nomeText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nomeText.setForeground(new java.awt.Color(0, 0, 0));
        nomeText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextActionPerformed(evt);
            }
        });
        nomeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeTextKeyReleased(evt);
            }
        });
        painelDataReposicao.add(nomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 230, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Senha:");
        painelDataReposicao.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 230, -1));

        jPanel1.add(painelDataReposicao);
        painelDataReposicao.setBounds(60, 110, 310, 190);

        botaoMenu.setBackground(new java.awt.Color(204, 0, 0));
        botaoMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoMenu.setForeground(new java.awt.Color(255, 255, 255));
        botaoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/VOLTAR.png"))); // NOI18N
        botaoMenu.setText("VOLTAR");
        botaoMenu.setToolTipText("Clique para voltar");
        botaoMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        botaoMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuActionPerformed(evt);
            }
        });
        jPanel1.add(botaoMenu);
        botaoMenu.setBounds(360, 320, 60, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        confirmar();            
    }//GEN-LAST:event_botaoConfirmarActionPerformed

    private void botaoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoMenuActionPerformed

    private void senhaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaTextActionPerformed
        confirmar();
    }//GEN-LAST:event_senhaTextActionPerformed

    private void senhaTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaTextKeyReleased
        digitacao();
    }//GEN-LAST:event_senhaTextKeyReleased

    private void nomeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeTextKeyReleased
        digitacao();
    }//GEN-LAST:event_nomeTextKeyReleased

    private void nomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextActionPerformed
       confirmar(); 
    }//GEN-LAST:event_nomeTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarUsuarioAtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarUsuarioAtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarUsuarioAtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarUsuarioAtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfirmarUsuarioAtual dialog = new ConfirmarUsuarioAtual(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bordaSalvar;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JButton botaoMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nomeText;
    private javax.swing.JDesktopPane painelDataReposicao;
    private javax.swing.JPasswordField senhaText;
    // End of variables declaration//GEN-END:variables
}
