/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela.Usuario;

import Classes.Funcoes;
import Classes.Usuario;
import Classes.UsuarioAtual;
import Classes.UsuarioNovo;
import Tela.Inicio.MenuPrincipal;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JRootPane;
import javax.swing.JSpinner;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

@SuppressWarnings("serial")
public class ConsultarUsuario extends javax.swing.JFrame {
    private final Funcoes funcao = new Funcoes();
    private final Usuario usuario = new Usuario();
    private final UsuarioNovo usuarioNovo = new UsuarioNovo();
    private final UsuarioAtual usuarioAtual = new UsuarioAtual();
    
    public ConsultarUsuario() {
        setUndecorated(true);
        initComponents();
        
        // Configura tabela (Nome, Email, Tipo)
        funcao.configurarTabela(tabelaUsuario, new Font("Tahoma", Font.BOLD, 14), Color.WHITE, new Color(0, 0, 102));
        
        pesquisarNome();
        pesquisarEmailUsuarioText.requestFocus();
        codigoText.getEditor().getComponent(0).setForeground(Color.BLACK);
        digitacao();
        
        funcao.aplicarEfeitoMouse(botaoEditar);
        funcao.aplicarEfeitoMouse(botaoMenu);
        
        adicionarAtalhosTeclado();
        adicionarLegendas();
    }
    
    private void pesquisarNome() {
        String emailParcial = pesquisarEmailUsuarioText.getText();

        List<Usuario> lista = usuario.buscarUsuarioPorNome(emailParcial, this);

        DefaultTableModel modelo = (DefaultTableModel) tabelaUsuario.getModel();
        modelo.setRowCount(0);

        for (Usuario u : lista) {
            String tipo = (u.isTipo()) ? "Administrador" : "Comum";
            
            modelo.addRow(new Object[]{
                u.getCodigo(),
                u.getNome(),
                u.getEmail(),
                tipo
            });
        }
        alinharTabela();
    }
    
    private void alinharTabela() {
        DefaultTableCellRenderer alinhamentoCentro = new DefaultTableCellRenderer();
        alinhamentoCentro.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tabelaUsuario.getColumnCount(); i++) {
            tabelaUsuario.getColumnModel().getColumn(i).setCellRenderer(alinhamentoCentro);
        }
    }
    
    private void editar(){
        long valor = Long.parseLong(codigoText.getValue().toString());
        if (valor == usuarioAtual.getCodigo()){
            funcao.Mensagens(this, "Por motivos de segurança", "você não pode alterar suas próprias permissões!", "SEM PERMISSÃO", "erro");
            return;
        }if (valor == 1){
            funcao.Mensagens(this, "Por motivos de segurança", "a ação de editar esse usuário é impossível!", "SEM PERMISSÃO", "erro");
            return;
        }
        // Preenche usuarioNovo com todos os dados
        if (usuario.consultarUsuario(valor, this)) {
            usuarioNovo.setCodigo(valor);
            usuarioNovo.setNome(usuario.getNome());
            usuarioNovo.setEmail(usuario.getEmail());
            usuarioNovo.setTipo(usuario.isTipo()); 
            usuarioNovo.setPermissoes(usuario.carregarPermissoes(valor));
            funcao.trocarDeTela(this, new EditarUsuario());
         } else {
            funcao.Mensagens(this, "Usuário não encontrado", "", "ERRO", "erro");
        }
    }

    private void digitacao(){
        funcao.entradaNumerica((JSpinner.DefaultEditor) codigoText.getEditor());
    }
    
    private void adicionarAtalhosTeclado() {
        JRootPane root = getRootPane();
        funcao.adicionarAtalho(root, "F12", botaoMenu);
        funcao.adicionarAtalho(root, "F1", botaoEditar);
        funcao.adicionarAtalhoTeclado(root, "F2", () -> codigoText.requestFocus());
        funcao.adicionarAtalhoTeclado(root, "F4", () -> pesquisarEmailUsuarioText.requestFocus());
    }
    
    private void adicionarLegendas() {
        funcao.validarBotaoComDica(botaoEditar, "Clique para editar permissão do usuário escolhido");
        funcao.validarSpinnerComDica(codigoText, "Escolha o código do usuário desejado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaoMenu = new javax.swing.JButton();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();
        pesquisarEmailUsuarioText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        codigoText = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        bordaSelecionar = new javax.swing.JPanel();
        botaoEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("ATALHOS: F1 = Selecionar Usuário para Editar | F2 = Digitar Código Usuário | F4 = Pesquisar E-mail do Usuário");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(4, 60, 1060, 16);

        jPanel2.setBackground(new java.awt.Color(210, 164, 2));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LogoMarca.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultarUsuario.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 8, 50, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CONSULTAR USUÁRIO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1070, -1));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1070, 60);

        botaoMenu.setBackground(new java.awt.Color(204, 0, 0));
        botaoMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoMenu.setForeground(new java.awt.Color(255, 255, 255));
        botaoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/home.png"))); // NOI18N
        botaoMenu.setText("MENU");
        botaoMenu.setToolTipText("Clique para voltar ao menu principal");
        botaoMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        botaoMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuActionPerformed(evt);
            }
        });
        jPanel1.add(botaoMenu);
        botaoMenu.setBounds(1002, 630, 60, 60);

        jDesktopPane3.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PESQUISAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 26), new java.awt.Color(0, 0, 102))); // NOI18N
        jDesktopPane3.setForeground(new java.awt.Color(0, 102, 153));
        jDesktopPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisarRegistrar.png"))); // NOI18N
        jLabel17.setOpaque(true);
        jDesktopPane3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 0, 30, 30));

        tabelaUsuario.setAutoCreateRowSorter(true);
        tabelaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        tabelaUsuario.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 16)); // NOI18N
        tabelaUsuario.setForeground(new java.awt.Color(51, 51, 51));
        tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "E-mail", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaUsuario.setSelectionBackground(new java.awt.Color(210, 164, 2));
        tabelaUsuario.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tabelaUsuario.getTableHeader().setReorderingAllowed(false);
        tabelaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaUsuarioKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaUsuario);
        if (tabelaUsuario.getColumnModel().getColumnCount() > 0) {
            tabelaUsuario.getColumnModel().getColumn(0).setPreferredWidth(5);
            tabelaUsuario.getColumnModel().getColumn(1).setPreferredWidth(170);
            tabelaUsuario.getColumnModel().getColumn(2).setPreferredWidth(350);
            tabelaUsuario.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        jDesktopPane3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 950, 380));

        pesquisarEmailUsuarioText.setBackground(new java.awt.Color(255, 255, 255));
        pesquisarEmailUsuarioText.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        pesquisarEmailUsuarioText.setForeground(new java.awt.Color(0, 0, 0));
        pesquisarEmailUsuarioText.setToolTipText("Pesquise usuário por e-mail");
        pesquisarEmailUsuarioText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisarEmailUsuarioTextKeyReleased(evt);
            }
        });
        jDesktopPane3.add(pesquisarEmailUsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 530, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("E-mail:");
        jDesktopPane3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 90, 40));

        jPanel1.add(jDesktopPane3);
        jDesktopPane3.setBounds(50, 90, 970, 480);

        jDesktopPane5.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "EDITAR PERMISSÃO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 26), new java.awt.Color(0, 0, 102))); // NOI18N
        jDesktopPane5.setFocusCycleRoot(false);
        jDesktopPane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        jLabel7.setOpaque(true);
        jDesktopPane5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, -1, 30, 30));

        codigoText.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 16)); // NOI18N
        codigoText.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(2L), Long.valueOf(2L), Long.valueOf(9223372036854775807L), Long.valueOf(1L)));
        codigoText.setToolTipText("");
        codigoText.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                codigoTextStateChanged(evt);
            }
        });
        codigoText.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                codigoTextInputMethodTextChanged(evt);
            }
        });
        codigoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoTextKeyTyped(evt);
            }
        });
        jDesktopPane5.add(codigoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 120, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Código:");
        jDesktopPane5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        bordaSelecionar.setBackground(new java.awt.Color(255, 255, 255));
        bordaSelecionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        bordaSelecionar.setForeground(new java.awt.Color(0, 0, 0));
        bordaSelecionar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoEditar.setBackground(new java.awt.Color(204, 204, 204));
        botaoEditar.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        botaoEditar.setForeground(new java.awt.Color(0, 0, 0));
        botaoEditar.setText("SELECIONAR");
        botaoEditar.setToolTipText("");
        botaoEditar.setBorder(null);
        botaoEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });
        bordaSelecionar.add(botaoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jDesktopPane5.add(bordaSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 140, 40));

        jPanel1.add(jDesktopPane5);
        jDesktopPane5.setBounds(10, 600, 430, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaUsuarioKeyPressed

    }//GEN-LAST:event_tabelaUsuarioKeyPressed

    private void botaoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuActionPerformed
        funcao.trocarDeTela(this, new MenuPrincipal());
    }//GEN-LAST:event_botaoMenuActionPerformed

    private void pesquisarEmailUsuarioTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisarEmailUsuarioTextKeyReleased
        pesquisarNome();
    }//GEN-LAST:event_pesquisarEmailUsuarioTextKeyReleased

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        editar();
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void codigoTextStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_codigoTextStateChanged
        digitacao();
    }//GEN-LAST:event_codigoTextStateChanged

    private void codigoTextInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_codigoTextInputMethodTextChanged

    }//GEN-LAST:event_codigoTextInputMethodTextChanged

    private void codigoTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTextKeyPressed

    }//GEN-LAST:event_codigoTextKeyPressed

    private void codigoTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTextKeyReleased

    }//GEN-LAST:event_codigoTextKeyReleased

    private void codigoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTextKeyTyped

    }//GEN-LAST:event_codigoTextKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bordaSelecionar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoMenu;
    private javax.swing.JSpinner codigoText;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pesquisarEmailUsuarioText;
    private javax.swing.JTable tabelaUsuario;
    // End of variables declaration//GEN-END:variables
}
